-- MySQL Script generated by MySQL Workbench
-- Fri Aug 20 22:03:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Studart_System
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Studart_System` ;

-- -----------------------------------------------------
-- Schema Studart_System
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Studart_System` DEFAULT CHARACTER SET utf8 ;
USE `Studart_System` ;

-- -----------------------------------------------------
-- Table `Studart_System`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Description` VARCHAR(200) NULL,
  `Status` VARCHAR(45) NOT NULL,
  `School` VARCHAR(45) NULL,
  `Image` LONGBLOB NULL,
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Type` (
  `TypeID` INT NOT NULL AUTO_INCREMENT,
  `TypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TypeID`),
  UNIQUE INDEX `TypeID_UNIQUE` (`TypeID` ASC) VISIBLE,
  UNIQUE INDEX `TypeName_UNIQUE` (`TypeName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Products` (
  `ProdID` INT NOT NULL,
  `ProdName` VARCHAR(50) NOT NULL,
  `ManufacDate` DATE NOT NULL,
  `ProdDescription` VARCHAR(200) NULL,
  `Price` DOUBLE NOT NULL,
  `ProductType` INT NOT NULL,
  `OwnerID` INT NOT NULL,
  PRIMARY KEY (`ProdID`),
  UNIQUE INDEX `ProdID_UNIQUE` (`ProdID` ASC) VISIBLE,
  INDEX `fk_Products_ProductType1_idx` (`ProductType` ASC) VISIBLE,
  INDEX `fk_Products_Users1_idx` (`OwnerID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_ProductType1`
    FOREIGN KEY (`ProductType`)
    REFERENCES `Studart_System`.`Type` (`TypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Users1`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `Studart_System`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Collections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Collections` (
  `UserID` INT NOT NULL,
  `ProdID` INT NOT NULL,
  `PurchaseDate` DATE NOT NULL,
  PRIMARY KEY (`UserID`, `ProdID`),
  INDEX `fk_Transaction_Products1_idx` (`ProdID` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Studart_System`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Products1`
    FOREIGN KEY (`ProdID`)
    REFERENCES `Studart_System`.`Products` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Admins` (
  `AdminID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(50) NULL,
  `Password` VARCHAR(200) NULL,
  PRIMARY KEY (`AdminID`),
  UNIQUE INDEX `AdminID_UNIQUE` (`AdminID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Styles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Styles` (
  `StyleID` INT NOT NULL,
  `StyleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StyleID`),
  UNIQUE INDEX `StyleName_UNIQUE` (`StyleName` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Images` (
  `ImageID` INT NOT NULL AUTO_INCREMENT,
  `Image` LONGBLOB NOT NULL,
  `ProdID` INT NOT NULL,
  PRIMARY KEY (`ImageID`),
  INDEX `fk_ProductImages_Products_idx` (`ProdID` ASC) VISIBLE,
  CONSTRAINT `fk_ProductImages_Products`
    FOREIGN KEY (`ProdID`)
    REFERENCES `Studart_System`.`Products` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`ProductStyles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`ProductStyles` (
  `ProdID` INT  NOT NULL,
  `StyleID` INT NOT NULL,
  PRIMARY KEY (`ProdID`, `StyleID`),
  INDEX `fk_Products_has_ProductStyles_ProductStyles1_idx` (`StyleID` ASC) VISIBLE,
  INDEX `fk_Products_has_ProductStyles_Products1_idx` (`ProdID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_ProductStyles_Products1`
    FOREIGN KEY (`ProdID`)
    REFERENCES `Studart_System`.`Products` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_ProductStyles_ProductStyles1`
    FOREIGN KEY (`StyleID`)
    REFERENCES `Studart_System`.`Styles` (`StyleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Favorlite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Favorlite` (
  `UserID` INT NOT NULL,
  `ProdID` INT  NOT NULL,
  PRIMARY KEY (`UserID`, `ProdID`),
  INDEX `fk_Users_has_Products_Users1_idx` (`UserID` ASC) VISIBLE,
  INDEX `fk_Cart_Products1_idx` (`ProdID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Products_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Studart_System`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_Products1`
    FOREIGN KEY (`ProdID`)
    REFERENCES `Studart_System`.`Products` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`TokensUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`TokensUser` (
  `TokensID` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(100) NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`TokensID`),
  UNIQUE INDEX `TokensID_UNIQUE` (`TokensID` ASC) VISIBLE,
  INDEX `fk_Tokens_Users1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Tokens_Users1`
    FOREIGN KEY (`UserID`)
    REFERENCES `Studart_System`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`TokensAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`TokensAdmin` (
  `TokensID` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(100) NOT NULL,
  `AdminID` INT NOT NULL,
  PRIMARY KEY (`TokensID`),
  UNIQUE INDEX `TokensID_UNIQUE` (`TokensID` ASC) VISIBLE,
  INDEX `fk_TokensAdmin_Admins1_idx` (`AdminID` ASC) VISIBLE,
  CONSTRAINT `fk_TokensAdmin_Admins1`
    FOREIGN KEY (`AdminID`)
    REFERENCES `Studart_System`.`Admins` (`AdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studart_System`.`Approval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Studart_System`.`Approval` (
  `AdminID` INT NOT NULL,
  `ProdID` INT NOT NULL,
  `Status` VARCHAR(30) NOT NULL,
  `DateApprove` DATE NOT NULL,
  PRIMARY KEY (`AdminID`, `ProdID`),
  INDEX `fk_Admins_has_Products_Products1_idx` (`ProdID` ASC) VISIBLE,
  INDEX `fk_Admins_has_Products_Admins1_idx` (`AdminID` ASC) VISIBLE,
  CONSTRAINT `fk_Admins_has_Products_Admins1`
    FOREIGN KEY (`AdminID`)
    REFERENCES `Studart_System`.`Admins` (`AdminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admins_has_Products_Products1`
    FOREIGN KEY (`ProdID`)
    REFERENCES `Studart_System`.`Products` (`ProdID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
