insert into studart_system.type (typeID,typeName)values(1,'Paint');
insert into studart_system.type (typeID,typeName)values(2,'Print');
insert into studart_system.type (typeID,typeName)values(3,'Draw');
insert into studart_system.type (typeID,typeName)values(4,'Photo');
insert into studart_system.type (typeID,typeName)values(5,'Graphic');
insert into studart_system.type (typeID,typeName)values(6,'3D');
insert into studart_system.type (typeID,typeName)values(7,'Combination');


insert into studart_system.styles (styleID,styleName)values(1,'Abstract');
insert into studart_system.styles (styleID,styleName)values(2,'Expressionism');
insert into studart_system.styles (styleID,styleName)values(3,'Impressionism');
insert into studart_system.styles (styleID,styleName)values(4,'Minimalism');
insert into studart_system.styles (styleID,styleName)values(5,'Classism');
insert into studart_system.styles (styleID,styleName)values(6,'Traditional');
insert into studart_system.styles (styleID,styleName)values(7,'Modern');
insert into studart_system.styles (styleID,styleName)values(8,'Art Deco');
insert into studart_system.styles (styleID,styleName)values(9,'Neoclassicism');
insert into studart_system.styles (styleID,styleName)values(10,'Conceptual');
insert into studart_system.styles (styleID,styleName)values(11,'Pop Art');
insert into studart_system.styles (styleID,styleName)values(12,'Architecture');
insert into studart_system.styles (styleID,styleName)values(13,'Fantasy');
insert into studart_system.styles (styleID,styleName)values(14,'Portrait');
insert into studart_system.styles (styleID,styleName)values(15,'Seascape');
insert into studart_system.styles (styleID,styleName)values(16,'Landscape');
insert into studart_system.styles (styleID,styleName)values(17,'Cityscape');
insert into studart_system.styles (styleID,styleName)values(18,'Composite');
insert into studart_system.styles (styleID,styleName)values(19,'Creative');
insert into studart_system.styles (styleID,styleName)values(20,'Flim');
insert into studart_system.styles (styleID,styleName)values(21,'Double exposure');
insert into studart_system.styles (styleID,styleName)values(22,'Macro');
insert into studart_system.styles (styleID,styleName)values(23,'Long exposure');
insert into studart_system.styles (styleID,styleName)values(24,'Street');
insert into studart_system.styles (styleID,styleName)values(25,'Time Lapse');
insert into studart_system.styles (styleID,styleName)values(26,'Perfomance Art');
insert into studart_system.styles (styleID,styleName)values(27,'Black and White');
insert into studart_system.styles (styleID,styleName)values(28,'Camdid');
insert into studart_system.styles (styleID,styleName)values(29,'Commercial');
insert into studart_system.styles (styleID,styleName)values(30,'Drone');
insert into studart_system.styles (styleID,styleName)values(31,'Lifestyle');
